import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Created with IntelliJ IDEA.
 * User: shafreen
 * Date: 10/3/13
 * Time: 2:30 PM
 */
public class echo extends HttpServlet {


    public static int COUNT = 0;

    public void init() throws ServletException
    {
        System.out.println(echo.class);
    }
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        StringBuffer content =new StringBuffer();

//        int d;
//        while((d=request.getInputStream().read()) != -1){
//            content.append((char)d);
//        }
//        System.out.println("----> " + request.getContentType() + " - " + content);

        // Set status code
        response.setStatus(200);
//        System.out.println("Sending the response with status code -> 200");

// ---------------------------------------------------------------------------------------------------------------------
//        Set response content type
        response.setContentType("application/json");

        // Actual logic goes here.
        PrintWriter out = response.getWriter();
        out.println("{\"Customer\":{\"name\":\"Jack\"}}");

        System.out.println("HIT #################");

        response.getOutputStream();
// ---------------------------------------------------------------------------------------------------------------------
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        int d;
        StringBuffer content =new StringBuffer();
        while((d=request.getInputStream().read()) != -1){
//            content.append((char)d);
            content.append("a");
        }

        response.setStatus(200);
        response.setContentType("application/xml");
//        response.setContentType(request.getContentType());
        PrintWriter out = response.getWriter();
        out.println("<a/>");
//        out.println(content);

//        out.println("<item><Verificationid>100000000000001</Verificationid><index>0</index><guid>90ee1227-0003-4a22-bbad-e5fba1d1cc69</guid><isActive>true</isActive><balance>$3,960.23</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>blue</eyeColor><name>Vasquez Cortez</name><gender>male</gender><company>OCEANICA</company><email>vasquezcortez@oceanica.com</email><phone>+1 (817) 538-2644</phone><address>932 Erskine Loop, Comptche, Iowa, 645</address><about>Fugiat est Lorem mollit pariatur culpa eu. In est velit magna id eiusmod veniam cupidatat. Esse commodo duis labore esse ipsum ut exercitation. Qui dolore cillum exercitation mollit dolore dolore laboris sit ea eiusmod adipisicing. Non ex do aliquip ex ullamco do cupidatat. Sint qui ut pariatur est duis consequat ex nulla do elit dolor eu occaecat. Consectetur non consequat ullamco amet.\n"
//                + "</about><registered>2017-09-06T04:16:16 -06:-30</registered><latitude>64.17767</latitude><longitude>58.03411</longitude><tags><item>duis</item><item>in</item><item>commodo</item><item>ad</item><item>dolor</item><item>reprehenderit</item><item>incididunt</item></tags><friends><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>0</id><name>Stacie Guerra</name></item><item><id>1</id><name>Claudine Jenkins</name></item><item><id>2</id><name>Jami Salas</name></item></friends><greeting>Hello, Vasquez Cortez! You have 6 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb34a135f019fd8fab1</_id><index>1</index><guid>d7129c1f-31ab-44f2-a817-3a6b10f01f25</guid><isActive>false</isActive><balance>$3,212.83</balance><picture>http://placehold.it/32x32</picture><age>26</age><eyeColor>blue</eyeColor><name>Penny Thomas</name><gender>female</gender><company>RODEOMAD</company><email>pennythomas@rodeomad.com</email><phone>+1 (995) 542-2414</phone><address>706 Dunne Court, Lowgap, Massachusetts, 5277</address><about>Officia reprehenderit tempor consectetur ea incididunt dolore. Elit elit sunt irure est commodo laboris ea commodo laborum enim cupidatat. Consequat consequat ullamco dolore ipsum sunt. Cupidatat excepteur commodo irure ea magna magna. Elit sunt cupidatat officia veniam culpa et velit veniam nostrud veniam voluptate laborum. Reprehenderit incididunt sint aliquip aute eiusmod ex cupidatat occaecat qui ad quis et aute.\n"
//                + "</about><registered>2014-09-18T10:37:26 -06:-30</registered><latitude>10.408161</latitude><longitude>-150.31191</longitude><tags><item>dolore</item><item>aliqua</item><item>anim</item><item>excepteur</item><item>eu</item><item>elit</item><item>aute</item></tags><friends><item><id>0</id><name>Patterson Riddle</name></item><item><id>1</id><name>Gates Mcmillan</name></item><item><id>2</id><name>Thompson Doyle</name></item></friends><greeting>Hello, Penny Thomas! You have 9 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb32ccbdb56d3d92842</_id><index>2</index><guid>5984213a-7e52-4907-be94-74081b14f607</guid><isActive>false</isActive><balance>$1,657.23</balance><picture>http://placehold.it/32x32</picture><age>39</age><eyeColor>brown</eyeColor><name>Blankenship Gilbert</name><gender>male</gender><company>ELECTONIC</company><email>blankenshipgilbert@electonic.com</email><phone>+1 (812) 434-3631</phone><address>817 Matthews Court, Lloyd, Texas, 9715</address><about>Commodo aliqua sunt laboris Lorem dolore ex ex nulla qui ut id ex. Ad esse non consectetur cillum aliqua fugiat consequat deserunt elit adipisicing. Sunt ullamco officia dolore enim cupidatat sit labore quis ullamco velit.\n"
//                + "</about><registered>2016-09-01T04:08:38 -06:-30</registered><latitude>6.932649</latitude><longitude>-171.858545</longitude><tags><item>aliqua</item><item>ut</item><item>cillum</item><item>adipisicing</item><item>laboris</item><item>excepteur</item><item>ad</item></tags><friends><item><id>0</id><name>Weeks Fulton</name></item><item><id>1</id><name>Emma Pate</name></item><item><id>2</id><name>Dianne Richardson</name></item></friends><greeting>Hello, Blankenship Gilbert! You have 9 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3a4fbaf46d4637be6</_id><index>3</index><guid>bb4f3ca0-1d05-415e-8593-07948e2bba0b</guid><isActive>false</isActive><balance>$3,624.06</balance><picture>http://placehold.it/32x32</picture><age>30</age><eyeColor>blue</eyeColor><name>Whitehead Lindsay</name><gender>male</gender><company>MOREGANIC</company><email>whiteheadlindsay@moreganic.com</email><phone>+1 (831) 574-3664</phone><address>327 Campus Road, Kersey, Nevada, 4570</address><about>Voluptate aliqua Lorem in sunt est tempor mollit occaecat sunt dolore minim laboris voluptate. Aliqua tempor eiusmod ipsum commodo sit ipsum tempor reprehenderit reprehenderit nisi nostrud et. Culpa aliquip ullamco enim ad ipsum labore velit.\n"
//                + "</about><registered>2017-06-04T01:36:40 -06:-30</registered><latitude>46.478692</latitude><longitude>79.547743</longitude><tags><item>sit</item><item>Lorem</item><item>velit</item><item>minim</item><item>Lorem</item><item>officia</item><item>aliqua</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Justice Robertson</name></item><item><id>1</id><name>Nichols Charles</name></item><item><id>2</id><name>Rebecca Foster</name></item></friends><greeting>Hello, Whitehead Lindsay! You have 3 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb3b51566f5ac684d83</_id><index>4</index><guid>fcf10788-ddbe-4cc6-a938-95d164adc276</guid><isActive>true</isActive><balance>$2,592.38</balance><picture>http://placehold.it/32x32</picture><age>35</age><eyeColor>green</eyeColor><name>Bette Ashley</name><gender>female</gender><company>COASH</company><email>betteashley@coash.com</email><phone>+1 (905) 512-3864</phone><address>678 Rockaway Parkway, Brownsville, California, 9538</address><about>Labore anim aliqua enim consectetur non proident do fugiat esse sunt. Incididunt consequat duis nulla duis qui magna. Amet anim officia consequat laboris non aliqua et nulla velit laborum duis.\n"
//                + "</about><registered>2017-04-17T12:51:09 -06:-30</registered><latitude>-85.967546</latitude><longitude>-179.284013</longitude><tags><item>do</item><item>cupidatat</item><item>eiusmod</item><item>laborum</item><item>amet</item><item>nisi</item><item>pariatur</item></tags><friends><item><id>0</id><name>Pansy Alvarez</name></item><item><id>1</id><name>Lesley Zamora</name></item><item><id>2</id><name>Jones Schmidt</name></item></friends><greeting>Hello, Bette Ashley! You have 6 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item><item><_id>5ad96cb37f48f6e942ecf7d0</_id><index>5</index><guid>4d3aee78-29d8-4b38-99b7-2868aeb5c221</guid><isActive>true</isActive><balance>$1,398.37</balance><picture>http://placehold.it/32x32</picture><age>29</age><eyeColor>blue</eyeColor><name>Jolene Moreno</name><gender>female</gender><company>DYMI</company><email>jolenemoreno@dymi.com</email><phone>+1 (894) 502-3031</phone><address>990 Turnbull Avenue, Davenport, Washington, 3045</address><about>Ullamco consequat fugiat sunt nisi minim. Ea anim deserunt aute ipsum excepteur officia. Ad labore elit duis aute quis dolor elit ullamco proident reprehenderit. Dolore qui exercitation deserunt aute fugiat laboris sit occaecat eiusmod. Est cillum dolore officia exercitation id nisi.\n"
//                + "</about><registered>2017-03-30T09:37:14 -06:-30</registered><latitude>-60.594023</latitude><longitude>-120.590648</longitude><tags><item>anim</item><item>aute</item><item>sint</item><item>Lorem</item><item>enim</item><item>eiusmod</item><item>eu</item></tags><friends><item><id>0</id><name>Marisa Buck</name></item><item><id>1</id><name>Deann Gutierrez</name></item><item><id>2</id><name>Gracie Bowers</name></item></friends><greeting>Hello, Jolene Moreno! You have 8 unread messages.</greeting><favoriteFruit>strawberry</favoriteFruit></item><item><_id>5ad96cb38f3fbf5b16ff28ee</_id><index>6</index><guid>94d040bb-3b67-4535-9206-0c1190225c27</guid><isActive>false</isActive><balance>$2,408.35</balance><picture>http://placehold.it/32x32</picture><age>38</age><eyeColor>green</eyeColor><name>Vang Franco</name><gender>male</gender><company>COMVEY</company><email>vangfranco@comvey.com</email><phone>+1 (959) 495-2068</phone><address>380 Milford Street, Stagecoach, Maine, 3475</address><about>Nisi magna in do exercitation. Sunt nisi quis exercitation sint consequat Lorem id. Sint nisi duis ut aliquip laboris cillum deserunt cillum nulla nulla eu minim. Excepteur consequat quis dolor deserunt pariatur commodo pariatur qui ullamco pariatur ut. Laborum consectetur exercitation dolor labore ut cupidatat sunt duis. Voluptate ex deserunt tempor consectetur veniam enim. Nostrud irure et est aute enim sint minim voluptate aliqua dolor quis.\n"
//                + "</about><registered>2014-07-08T01:37:23 -06:-30</registered><latitude>-41.378847</latitude><longitude>147.812281</longitude><tags><item>aliqua</item><item>incididunt</item><item>ullamco</item><item>est</item><item>ad</item><item>adipisicing</item><item>elit</item></tags><friends><item><id>0</id><name>Emilia Walls</name></item><item><id>1</id><name>Spears Reyes</name></item><item><id>2</id><name>Coffey Ross</name></item></friends><greeting>Hello, Vang Franco! You have 10 unread messages.</greeting><favoriteFruit>banana</favoriteFruit></item>");
    }

    public void destroy()
    {
        // do nothing.
    }
}
